[package]
name = "astral_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
front = { path = "./front" }

[workspace]
members = [
    "front",
    "front_parse",
    "front_verify_structure",
    "front_verify_types",
]
